name: McXyhj
version: ${project.version}
main: cn.mcxyhj.knkiss.McXyhj
api-version: 1.17
authors: [Knkiss, Dnkiss]
description: Plugins For McXyhj
website: www.mcxyhj.cn
depend: [Vault]

commands:
  mcxyhj:
    description: a command to
    usage: /mcxyhj
  flyenergy:
    description: a command to start fly energy
    usage: /flyEnergy
    aliases: fe
  bd:
    description: a command to close or open scoreboard forever
    usage: /bd
  slg:
    description: a command to play SwapLocationGame
    usage: /slg
  armor:
    description: a command to set or get player's armor
    usage: /armor

Permissions:
  mcxyhj.zhengban.fly:
    description: 用于特价购买飞行能量

